services:
  next-1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3000"

  next-2:
    build:
      context: .
      dockerfile: Dockerfile2
    ports:
      - "3002:3000"

  nginx:
    image: nginx:latest
    ports:
      - "3000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - next-1
      - next-2
